version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - ./mongodb_data/:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  
  cards:
    build: ./cards/
    volumes:
      - ./cards:/app
    ports:
      - 21450:21450
    command: nodemon index.js
